/**
 * Aurelisse — L'Éclat de l'Élégance
 * Master Luxury Data Repository (100% Curated & Verified Jewellery Imagery)
 * 15+ Years Award-Winning Senior UI/UX & Frontend Architecture
 */

export const BRAND_CONFIG = {
  name: "Aurelisse",
  tagline: "L'Éclat de l'Élégance",
  subTagline: "The Brilliance of Elegance",
  founded: "1894",
  headquarters: "Place Vendôme, Paris",
  phone: "+33 1 42 60 88 00",
  whatsappNumber: "33142608800",
  email: "concierge@aurelisse.com",
  currency: "$",
  freeShippingThreshold: 2500,
  taxRate: 0.08,
  giftWrapCost: 35
};

export const CURRENCY_RATES = {
  USD: { symbol: "$", rate: 1.0 },
  EUR: { symbol: "€", rate: 0.92 },
  GBP: { symbol: "£", rate: 0.79 },
  JPY: { symbol: "¥", rate: 156.5 }
};

export const HERO_SLIDES = [
  {
    id: 1,
    title: "The Royal Impériale Solitaire",
    subtitle: "HIGH JEWELLERY • PLACE VENDÔME COLLECTION",
    description: "An extraordinary 4.2-carat D-Flawless emerald-cut diamond set in handcrafted 18K Platinum with pavé diamond accents. Designed for eternity.",
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1920&q=85",
    link: "#product-details?id=ring-solitaire-imp-01",
    ctaText: "Discover the Impériale",
    secondaryCta: "#categories",
    secondaryCtaText: "Explore Collections"
  },
  {
    id: 2,
    title: "L'Aurore Éternelle Diamond Collier",
    subtitle: "THE BRIDAL MASTERPIECE",
    description: "Featuring 38 carats of brilliant-cut and pear-shaped diamonds suspended in a cascade of pure 18K White Gold, capturing the first light of dawn.",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1920&q=85",
    link: "#product-details?id=neck-bridal-aur-01",
    ctaText: "View Bridal Collection",
    secondaryCta: "#products?category=Bridal%20Collection",
    secondaryCtaText: "Shop All Bridal"
  },
  {
    id: 3,
    title: "Céleste Sapphire & Diamond Chandelier",
    subtitle: "ROYAL GEMSTONE ARCHIVE",
    description: "Unrivaled deep royal blue Kashmir-shade sapphires embraced by pear-cut diamonds in articulated 18K White Gold settings.",
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1920&q=85",
    link: "#product-details?id=ear-drop-cel-01",
    ctaText: "Explore High Gemstones",
    secondaryCta: "#products?category=Gemstone%20Collection",
    secondaryCtaText: "Shop Earrings"
  }
];

export const CATEGORIES = [
  { id: "Rings", name: "Rings", count: 16, image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=600&q=80", desc: "Solitaires, Engagement & Cocktail Masterpieces" },
  { id: "Necklaces", name: "Necklaces", count: 14, image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=600&q=80", desc: "Pendants, Chokers & Layered Gold Chains" },
  { id: "Earrings", name: "Earrings", count: 12, image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80", desc: "Diamond Studs, Hoops & Chandelier Drops" },
  { id: "Bracelets", name: "Bracelets", count: 10, image: "https://images.unsplash.com/photo-1611591471483-ed5f36e8979d?auto=format&fit=crop&w=600&q=80", desc: "Diamond Tennis Bracelets & Handcrafted Bangles" },
  { id: "Bridal Collection", name: "Bridal Collection", count: 12, image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=600&q=80", desc: "Bespoke Engagement Rings & Heritage Wedding Sets" },
  { id: "Men's Jewellery", name: "Men's Jewellery", count: 8, image: "https://images.unsplash.com/photo-1622434641406-a158123450f9?auto=format&fit=crop&w=600&q=80", desc: "Signet Rings, Platinum Chains & Diamond Cufflinks" },
  { id: "Kids' Jewellery", name: "Kids' Jewellery", count: 6, image: "https://images.unsplash.com/photo-1543294001-f7cd5d7fb516?auto=format&fit=crop&w=600&q=80", desc: "Delicate 18K Gold Keepsakes & Baby Bangles" },
  { id: "Gold Collection", name: "Gold Collection", count: 18, image: "https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=600&q=80", desc: "Pure 18K & 24K Yellow, White & Rose Gold Works" },
  { id: "Diamond Collection", name: "Diamond Collection", count: 22, image: "https://images.unsplash.com/photo-1598560917505-59a3655c1592?auto=format&fit=crop&w=600&q=80", desc: "GIA Certified VVS Flawless Diamond Creations" },
  { id: "Gemstone Collection", name: "Gemstone Collection", count: 14, image: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=600&q=80", desc: "Colombian Emeralds, Burmese Rubies & Sapphires" },
  { id: "Pearl Collection", name: "Pearl Collection", count: 8, image: "https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?auto=format&fit=crop&w=600&q=80", desc: "Akoya, South Sea & Tahitian Cultured Pearls" },
  { id: "Platinum Collection", name: "Platinum Collection", count: 12, image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=600&q=80", desc: "PT950 Pure Heritage Platinum Creations" },
  { id: "Everyday Wear", name: "Everyday Wear", count: 16, image: "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=600&q=80", desc: "Subtle Luxury for Daily Modern Elegance" },
  { id: "Statement Pieces", name: "Statement Pieces", count: 12, image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=600&q=80", desc: "Bold High-Jewellery Masterpieces for Gala Evenings" },
  { id: "Minimal/Layering Pieces", name: "Minimal/Layering Pieces", count: 14, image: "https://images.unsplash.com/photo-1611591471898-250be0680a6b?auto=format&fit=crop&w=600&q=80", desc: "Fine Chains & Stackable Rings for Effortless Layering" },
  { id: "Anniversary Collection", name: "Anniversary Collection", count: 10, image: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=600&q=80", desc: "Eternity Bands & Commemorative Diamond Gifts" },
  { id: "Custom/Bespoke Jewellery", name: "Custom/Bespoke Jewellery", count: 6, image: "https://images.unsplash.com/photo-1598560917505-59a3655c1592?auto=format&fit=crop&w=600&q=80", desc: "Collaborate with Our Place Vendôme Master Jewelers" },
  { id: "Vintage-Inspired Collection", name: "Vintage-Inspired Collection", count: 8, image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80", desc: "Art Deco & Belle Époque Heritage Reproductions" },
  { id: "Watches", name: "Watches", count: 6, image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=600&q=80", desc: "Swiss Mechanical Complications & Pavé Timepieces" },
  { id: "Accessories", name: "Accessories", count: 6, image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=600&q=80", desc: "Italian Velvet Jewellery Boxes & Care Kits" }
];

export const PRODUCTS = [
  // --- RINGS ---
  {
    id: "ring-solitaire-imp-01",
    name: "The Royal Impériale Solitaire Ring",
    brand: "Aurelisse Haute Joaillerie",
    category: "Rings",
    subcategory: "Solitaire Rings",
    collections: ["Rings", "Diamond Collection", "Platinum Collection", "Bridal Collection", "Statement Pieces", "Anniversary Collection"],
    price: 38500,
    originalPrice: 42000,
    discount: 8,
    rating: 5.0,
    reviewsCount: 28,
    stockStatus: "In Stock (Only 2 Crafted)",
    isNew: true,
    isBestSeller: true,
    isTrending: true,
    isBridalPick: true,
    badge: "Limited Edition",
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=85",
    images: [
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=1200&q=85"
    ],
    metals: ["Platinum (PT950)", "18K White Gold", "18K Yellow Gold"],
    sizes: ["US 4.5", "US 5", "US 5.5", "US 6", "US 6.5", "US 7"],
    description: "The crown jewel of our Place Vendôme archive. A mesmerizing 4.2-carat D-Flawless emerald-cut diamond mounted upon a solid PT950 Platinum band intricately hand-set with micro-pavé diamonds.",
    specs: { material: "PT950 Solid Platinum / 18K Gold", hallmark: "AURELISSE 950 PT / GIA Certified", weight: "7.8 grams", gemstone: "Natural Diamond • Emerald Cut • 4.20 Carats • D • FL Flawless" }
  },
  {
    id: "ring-eng-celeste-02",
    name: "Céleste Oval Diamond Engagement Ring",
    brand: "Aurelisse Bridal",
    category: "Rings",
    subcategory: "Engagement Rings",
    collections: ["Rings", "Bridal Collection", "Diamond Collection", "Anniversary Collection", "Custom/Bespoke Jewellery"],
    price: 18900,
    originalPrice: 21000,
    discount: 10,
    rating: 4.9,
    reviewsCount: 42,
    stockStatus: "In Stock",
    isNew: false,
    isBestSeller: true,
    isTrending: true,
    isBridalPick: true,
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=1200&q=85"],
    metals: ["18K White Gold", "18K Yellow Gold", "18K Rose Gold", "Platinum (PT950)"],
    sizes: ["US 4", "US 4.5", "US 5", "US 5.5", "US 6", "US 6.5", "US 7"],
    description: "An ethereal 2.50-carat oval brilliant diamond set upon a delicate knife-edge 18K gold shank with hidden halo diamonds beneath the gallery.",
    specs: { material: "18K Gold or PT950 Platinum", hallmark: "AURELISSE 750 / GIA Certified", weight: "5.4 grams", gemstone: "Natural Diamond • Oval Cut • 2.50 Carats • E • VVS1" }
  },
  {
    id: "ring-eternity-lum-03",
    name: "Lumière Éternelle Diamond Band",
    brand: "Aurelisse Classics",
    category: "Rings",
    subcategory: "Eternity Bands",
    collections: ["Rings", "Anniversary Collection", "Diamond Collection", "Bridal Collection", "Everyday Wear"],
    price: 6400,
    originalPrice: 6400,
    discount: 0,
    rating: 4.9,
    reviewsCount: 34,
    stockStatus: "In Stock",
    isNew: false,
    isBestSeller: true,
    isTrending: false,
    isBridalPick: true,
    badge: "Bridal Pick",
    image: "https://images.unsplash.com/photo-1598560917505-59a3655c1592?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1598560917505-59a3655c1592?auto=format&fit=crop&w=1200&q=85"],
    metals: ["18K Yellow Gold", "18K White Gold", "Platinum (PT950)"],
    sizes: ["US 4.5", "US 5", "US 5.5", "US 6", "US 6.5", "US 7"],
    description: "An unbroken circle of radiant emerald-cut diamonds totaling 3.8 carats, secured in a shared-prong minimal setting that maximizes light entry from every angle.",
    specs: { material: "18K Gold or PT950 Platinum", hallmark: "AURELISSE 750", weight: "6.1 grams", gemstone: "Natural Diamonds • 18 Emerald Cuts • Total 3.80 Carats • F • VS1" }
  },
  {
    id: "ring-cocktail-em-04",
    name: "L'Émeraude Royale Cocktail Ring",
    brand: "Aurelisse High Gemstones",
    category: "Rings",
    subcategory: "Cocktail Rings",
    collections: ["Rings", "Gemstone Collection", "Statement Pieces", "Gold Collection", "Vintage-Inspired Collection"],
    price: 24500,
    originalPrice: 28000,
    discount: 12.5,
    rating: 5.0,
    reviewsCount: 19,
    stockStatus: "In Stock (1 Available)",
    isNew: true,
    isBestSeller: false,
    isTrending: true,
    isBridalPick: false,
    badge: "Trending",
    image: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=1200&q=85"],
    metals: ["18K Yellow Gold", "Platinum (PT950)"],
    sizes: ["US 5", "US 6", "US 6.5", "US 7"],
    description: "A vivid green 5.1-carat untreated Muzo Colombian Emerald encircled by a double sunburst halo of marquise and round brilliant diamonds.",
    specs: { material: "18K Yellow Gold & Platinum", hallmark: "AURELISSE 750 / Gubelin Certified", weight: "9.2 grams", gemstone: "Natural Colombian Emerald • 5.10 Cts • Untreated • 1.8 Cts Diamond Halo" }
  },
  {
    id: "ring-stack-rose-05",
    name: "Petite Aurore Rose Gold Stackable Ring",
    brand: "Aurelisse Everyday",
    category: "Rings",
    subcategory: "Stackable Rings",
    collections: ["Rings", "Everyday Wear", "Minimal/Layering Pieces", "Gold Collection"],
    price: 1850,
    originalPrice: 1850,
    discount: 0,
    rating: 4.8,
    reviewsCount: 56,
    stockStatus: "In Stock",
    isNew: false,
    isBestSeller: true,
    isTrending: false,
    isBridalPick: false,
    badge: "Everyday Luxury",
    image: "https://images.unsplash.com/photo-1611591471898-250be0680a6b?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1611591471898-250be0680a6b?auto=format&fit=crop&w=1200&q=85"],
    metals: ["18K Rose Gold", "18K Yellow Gold", "18K White Gold"],
    sizes: ["US 4.5", "US 5", "US 5.5", "US 6", "US 6.5", "US 7"],
    description: "A finely sculpted twisted ribbon of 18K Rose Gold alternating with polished beads and grain-set micro diamonds. Designed to stack flawlessly.",
    specs: { material: "18K Solid Rose Gold", hallmark: "AURELISSE 750", weight: "3.2 grams", gemstone: "Natural Diamonds • 0.35 Cts Total • F • VS1" }
  },
  {
    id: "ring-vintage-sapphire-06",
    name: "Belle Époque Sapphire & Diamond Dome Ring",
    brand: "Aurelisse Heritage",
    category: "Rings",
    subcategory: "Cocktail Rings",
    collections: ["Rings", "Vintage-Inspired Collection", "Gemstone Collection", "Statement Pieces"],
    price: 14200,
    originalPrice: 15800,
    discount: 10,
    rating: 5.0,
    reviewsCount: 14,
    stockStatus: "In Stock",
    isNew: true,
    isBestSeller: false,
    isTrending: true,
    isBridalPick: false,
    badge: "Vintage Archive",
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1200&q=85"],
    metals: ["18K White Gold", "Platinum (PT950)"],
    sizes: ["US 5", "US 6", "US 7"],
    description: "Art Deco geometric filigree dome ring centered around a deep royal blue 3.10ct cushion-cut Ceylon sapphire, surrounded by milgrain diamond borders.",
    specs: { material: "18K White Gold", hallmark: "AURELISSE 750 ARCHIVE", weight: "7.5 grams", gemstone: "Natural Ceylon Sapphire (3.10 Cts) & 1.10 Cts VS Diamonds" }
  },

  // --- BRACELETS ---
  {
    id: "brac-tennis-riv-01",
    name: "Rivière d'Étoiles Diamond Tennis Bracelet",
    brand: "Aurelisse Classics",
    category: "Bracelets",
    subcategory: "Tennis Bracelets",
    collections: ["Bracelets", "Diamond Collection", "Platinum Collection", "Bridal Collection", "Statement Pieces", "Anniversary Collection"],
    price: 16500,
    originalPrice: 18000,
    discount: 8.3,
    rating: 5.0,
    reviewsCount: 61,
    stockStatus: "In Stock",
    isNew: false,
    isBestSeller: true,
    isTrending: true,
    isBridalPick: true,
    badge: "Iconic",
    image: "https://images.unsplash.com/photo-1611591471483-ed5f36e8979d?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1611591471483-ed5f36e8979d?auto=format&fit=crop&w=1200&q=85"],
    metals: ["18K White Gold", "18K Yellow Gold", "Platinum (PT950)"],
    sizes: ["6.5 Inches (Small)", "7.0 Inches (Medium)", "7.5 Inches (Large)"],
    description: "A seamless stream of 55 individually matched F-color diamonds totaling 7.50 carats, each cradled in a supple 4-prong articulation that flows like liquid light along the wrist.",
    specs: { material: "18K White Gold / PT950", hallmark: "AURELISSE 750 / Double Safety Latch", weight: "14.2 grams", gemstone: "55 Natural Diamonds • 7.50 Carats Total • F • VVS2" }
  },
  {
    id: "brac-bangle-gold-02",
    name: "L'Architecte Gold & Diamond Hinged Bangle",
    brand: "Aurelisse Gold Collection",
    category: "Bracelets",
    subcategory: "Bangles",
    collections: ["Bracelets", "Gold Collection", "Everyday Wear", "Minimal/Layering Pieces", "Statement Pieces"],
    price: 9400,
    originalPrice: 9400,
    discount: 0,
    rating: 4.9,
    reviewsCount: 37,
    stockStatus: "In Stock",
    isNew: true,
    isBestSeller: false,
    isTrending: true,
    isBridalPick: false,
    badge: "New Release",
    image: "https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=1200&q=85"],
    metals: ["18K Yellow Gold", "18K Rose Gold"],
    sizes: ["Size 16 (Small)", "Size 17 (Medium)", "Size 18 (Large)"],
    description: "Sculptural solid 18K gold oval bangle featuring our signature fluted texture and a focal bridge set with 1.2 carats of baguette-cut diamonds.",
    specs: { material: "Solid 18K Yellow Gold", hallmark: "AURELISSE 750", weight: "26.4 grams", gemstone: "Natural Baguette Diamonds • 1.20 Carats • E-F • VVS" }
  },
  {
    id: "brac-pearl-akoya-03",
    name: "Impératrice Akoya Pearl & Diamond Bracelet",
    brand: "Aurelisse Pearl Collection",
    category: "Bracelets",
    subcategory: "Charm Bracelets",
    collections: ["Bracelets", "Pearl Collection", "Bridal Collection", "Vintage-Inspired Collection", "Everyday Wear"],
    price: 5800,
    originalPrice: 6400,
    discount: 9.3,
    rating: 4.9,
    reviewsCount: 29,
    stockStatus: "In Stock",
    isNew: false,
    isBestSeller: true,
    isTrending: false,
    isBridalPick: true,
    badge: "Pearl Heritage",
    image: "https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?auto=format&fit=crop&w=1200&q=85"],
    metals: ["18K White Gold", "18K Yellow Gold"],
    sizes: ["6.5 Inches", "7.0 Inches"],
    description: "Double strand of AAA lustrous Japanese Akoya pearls (7.5mm) joined by an 18K gold Art Deco clasp encrusted with 0.65 carats of brilliant diamonds.",
    specs: { material: "18K Gold Clasp & Silk Threading", hallmark: "AURELISSE 750 PEARL", weight: "19.5 grams", gemstone: "AAA Akoya Pearls (7.5mm) & 0.65 Cts Pavé Diamonds" }
  },
  {
    id: "brac-cuff-emerald-04",
    name: "Vendôme Emerald & Gold Architectural Cuff",
    brand: "Aurelisse High Gemstones",
    category: "Bracelets",
    subcategory: "Cuffs",
    collections: ["Bracelets", "Gemstone Collection", "Statement Pieces", "Gold Collection", "Custom/Bespoke Jewellery"],
    price: 21000,
    originalPrice: 23500,
    discount: 10.6,
    rating: 5.0,
    reviewsCount: 16,
    stockStatus: "In Stock (Only 1 Left)",
    isNew: true,
    isBestSeller: false,
    isTrending: true,
    isBridalPick: false,
    badge: "High Gemstone",
    image: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=1200&q=85"],
    metals: ["18K Yellow Gold"],
    sizes: ["Adjustable Cuff Fit (6.0 - 7.5 Inches)"],
    description: "Substantial solid 18K gold wide cuff with openwork Parisian trellis design, capped with two matched 1.8-carat Colombian emerald cabochons and diamond halos.",
    specs: { material: "18K Solid Yellow Gold", hallmark: "AURELISSE 750 HIGH JEWELLERY", weight: "44.2 grams", gemstone: "Matched Colombian Emeralds • 3.60 Cts Total & 1.4 Cts Diamonds" }
  },
  {
    id: "brac-chain-layer-05",
    name: "Chaîne d'Or Minimalist Link Bracelet",
    brand: "Aurelisse Everyday",
    category: "Bracelets",
    subcategory: "Chain Bracelets",
    collections: ["Bracelets", "Everyday Wear", "Minimal/Layering Pieces", "Gold Collection"],
    price: 2200,
    originalPrice: 2200,
    discount: 0,
    rating: 4.8,
    reviewsCount: 52,
    stockStatus: "In Stock",
    isNew: false,
    isBestSeller: true,
    isTrending: false,
    isBridalPick: false,
    badge: "Essential",
    image: "https://images.unsplash.com/photo-1611591471898-250be0680a6b?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1611591471898-250be0680a6b?auto=format&fit=crop&w=1200&q=85"],
    metals: ["18K Yellow Gold", "18K Rose Gold", "18K White Gold"],
    sizes: ["6.5 Inches", "7.0 Inches", "7.5 Inches"],
    description: "Polished elongated knife-edge oval links in solid 18K gold. An effortless daily staple designed to stack with watches and tennis bracelets.",
    specs: { material: "Solid 18K Gold", hallmark: "AURELISSE 750", weight: "12.8 grams", gemstone: "Pure Precious Metal" }
  },
  {
    id: "brac-plat-diamond-06",
    name: "PT950 Platinum Art Deco Pavé Bangle",
    brand: "Aurelisse Platinum Archive",
    category: "Bracelets",
    subcategory: "Bangles",
    collections: ["Bracelets", "Platinum Collection", "Diamond Collection", "Vintage-Inspired Collection", "Anniversary Collection"],
    price: 18500,
    originalPrice: 20000,
    discount: 7.5,
    rating: 5.0,
    reviewsCount: 23,
    stockStatus: "In Stock",
    isNew: true,
    isBestSeller: false,
    isTrending: true,
    isBridalPick: false,
    badge: "Platinum Heritage",
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=85"],
    metals: ["Platinum (PT950)"],
    sizes: ["Size 16", "Size 17"],
    description: "Forged in pure PT950 Platinum, this rigid hinged bangle features intricate Art Deco geometric engravings set with 3.20 carats of F-color brilliant diamonds.",
    specs: { material: "Pure PT950 Platinum", hallmark: "AURELISSE 950 PT", weight: "32.0 grams", gemstone: "Natural Diamonds • 3.20 Carats • F • VVS1" }
  },

  // --- NECKLACES ---
  {
    id: "neck-bridal-aur-01",
    name: "L'Aurore Éternelle Diamond Rivière Necklace",
    brand: "Aurelisse High Jewellery",
    category: "Necklaces",
    subcategory: "Bridal Necklace Sets",
    collections: ["Necklaces", "Bridal Collection", "Diamond Collection", "Statement Pieces", "Platinum Collection"],
    price: 78000,
    originalPrice: 85000,
    discount: 8.2,
    rating: 5.0,
    reviewsCount: 14,
    stockStatus: "In Stock (1 Masterpiece)",
    isNew: true,
    isBestSeller: true,
    isTrending: true,
    isBridalPick: true,
    badge: "Masterpiece",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1200&q=85"],
    metals: ["18K White Gold", "Platinum (PT950)"],
    sizes: ["16 Inches (Choker Fit)", "18 Inches (Standard)"],
    description: "A monumental high-jewellery achievement. Over 38 carats of graduated pear-cut and round brilliant diamonds cascading from a supple articulated 18K White Gold lattice.",
    specs: { material: "18K White Gold", hallmark: "AURELISSE 750 HIGH JEWELLERY", weight: "48.2 grams", gemstone: "72 Natural Diamonds • Total 38.40 Carats • D-E • VVS1-FL Flawless" }
  },
  {
    id: "neck-pend-sol-02",
    name: "Goutte d'Or Solitaire Diamond Pendant",
    brand: "Aurelisse Classics",
    category: "Necklaces",
    subcategory: "Pendants",
    collections: ["Necklaces", "Diamond Collection", "Everyday Wear", "Minimal/Layering Pieces", "Gold Collection"],
    price: 4950,
    originalPrice: 4950,
    discount: 0,
    rating: 4.9,
    reviewsCount: 68,
    stockStatus: "In Stock",
    isNew: false,
    isBestSeller: true,
    isTrending: true,
    isBridalPick: false,
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1200&q=85"],
    metals: ["18K Yellow Gold", "18K White Gold", "18K Rose Gold"],
    sizes: ["16-18 Inches Adjustable"],
    description: "A brilliant 1.20-carat round diamond suspended inside a sleek, architectural gold bezel that slides effortlessly along a diamond-cut cable chain.",
    specs: { material: "18K Solid Gold Chain & Pendant", hallmark: "AURELISSE 750", weight: "4.8 grams", gemstone: "Natural Diamond • 1.20 Cts • F • VVS2 • Excellent Cut" }
  },
  {
    id: "neck-choker-pearl-03",
    name: "L'Impératrice Akoya Pearl & Diamond Choker",
    brand: "Aurelisse Pearl Collection",
    category: "Necklaces",
    subcategory: "Chokers",
    collections: ["Necklaces", "Pearl Collection", "Bridal Collection", "Statement Pieces", "Vintage-Inspired Collection"],
    price: 11200,
    originalPrice: 12500,
    discount: 10.4,
    rating: 4.9,
    reviewsCount: 25,
    stockStatus: "In Stock",
    isNew: true,
    isBestSeller: false,
    isTrending: true,
    isBridalPick: true,
    badge: "Bridal Pick",
    image: "https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?auto=format&fit=crop&w=1200&q=85"],
    metals: ["18K White Gold"],
    sizes: ["15 Inches (Choker Fit)"],
    description: "Three lustrous strands of perfectly matched AAA Japanese Akoya cultured pearls (8.5mm), united by an intricate Art Deco diamond clasp in 18K White Gold.",
    specs: { material: "18K White Gold Clasp & Silk Threading", hallmark: "AURELISSE 750", weight: "52.0 grams", gemstone: "AAA Japanese Akoya Pearls (8.5mm) & 1.80 Cts Pavé Diamonds" }
  },
  {
    id: "neck-chain-her-04",
    name: "Chaîne Royale 18K Gold Link Necklace",
    brand: "Aurelisse Gold Archive",
    category: "Necklaces",
    subcategory: "Chains",
    collections: ["Necklaces", "Gold Collection", "Everyday Wear", "Minimal/Layering Pieces"],
    price: 6800,
    originalPrice: 6800,
    discount: 0,
    rating: 4.8,
    reviewsCount: 39,
    stockStatus: "In Stock",
    isNew: false,
    isBestSeller: false,
    isTrending: false,
    isBridalPick: false,
    badge: "Heritage Gold",
    image: "https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=1200&q=85"],
    metals: ["18K Yellow Gold"],
    sizes: ["18 Inches", "20 Inches", "24 Inches"],
    description: "Solid 18K gold elongated links forged with our signature knife-edge bevel and high-mirror hand polish. A statement alone or layered with pendants.",
    specs: { material: "Solid 18K Yellow Gold", hallmark: "AURELISSE 750 FRANCE", weight: "34.5 grams (18 inch)", gemstone: "None (Pure Precious Metal)" }
  },
  {
    id: "neck-ruby-fire-05",
    name: "L'Oiseau de Feu Burmese Ruby Choker",
    brand: "Aurelisse High Gemstones",
    category: "Necklaces",
    subcategory: "Chokers",
    collections: ["Necklaces", "Gemstone Collection", "Statement Pieces", "Vintage-Inspired Collection"],
    price: 32000,
    originalPrice: 35000,
    discount: 8.5,
    rating: 5.0,
    reviewsCount: 11,
    stockStatus: "In Stock (1 Masterpiece)",
    isNew: true,
    isBestSeller: false,
    isTrending: true,
    isBridalPick: false,
    badge: "Rare Gemstone",
    image: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=1200&q=85"],
    metals: ["18K White Gold", "Platinum (PT950)"],
    sizes: ["16 Inches"],
    description: "Featuring a breathtaking 3.4-carat unheated Pigeon's Blood Burmese Ruby suspended from a cluster of pear and marquise diamonds totaling 2.2 carats.",
    specs: { material: "18K White Gold & Platinum", hallmark: "AURELISSE 750 / SSEF Swiss Lab", weight: "18.9 grams", gemstone: "Unheated Burmese Ruby (3.40 Cts) & 2.20 Cts Flawless Diamonds" }
  },

  // --- EARRINGS ---
  {
    id: "ear-drop-cel-01",
    name: "Céleste Royal Sapphire Chandelier Earrings",
    brand: "Aurelisse High Gemstones",
    category: "Earrings",
    subcategory: "Chandelier Earrings",
    collections: ["Earrings", "Gemstone Collection", "Statement Pieces", "Bridal Collection", "Platinum Collection"],
    price: 45000,
    originalPrice: 48000,
    discount: 6.2,
    rating: 5.0,
    reviewsCount: 17,
    stockStatus: "In Stock (1 Pair Left)",
    isNew: true,
    isBestSeller: false,
    isTrending: true,
    isBridalPick: true,
    badge: "High Jewellery",
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1200&q=85"],
    metals: ["18K White Gold", "Platinum (PT950)"],
    sizes: ["2.4 Inches Drop Length"],
    description: "Staggering articulated drop earrings showcasing 8.4 carats of matched pear-cut Royal Blue sapphires from Sri Lanka, surrounded by 4.2 carats of marquise diamond clusters.",
    specs: { material: "18K White Gold", hallmark: "AURELISSE 750 HIGH JEWELLERY", weight: "18.4 grams per pair", gemstone: "Natural Sri Lankan Sapphires • 8.40 Cts Total & 4.20 Cts Diamonds" }
  },
  {
    id: "ear-stud-dia-02",
    name: "Vendôme Classic Solitaire Diamond Studs",
    brand: "Aurelisse Classics",
    category: "Earrings",
    subcategory: "Studs",
    collections: ["Earrings", "Diamond Collection", "Everyday Wear", "Minimal/Layering Pieces", "Platinum Collection"],
    price: 8900,
    originalPrice: 8900,
    discount: 0,
    rating: 5.0,
    reviewsCount: 92,
    stockStatus: "In Stock",
    isNew: false,
    isBestSeller: true,
    isTrending: false,
    isBridalPick: true,
    badge: "Essential Luxury",
    image: "https://images.unsplash.com/photo-1598560917505-59a3655c1592?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1598560917505-59a3655c1592?auto=format&fit=crop&w=1200&q=85"],
    metals: ["18K White Gold", "18K Yellow Gold", "Platinum (PT950)"],
    sizes: ["2.00 Cts Total (1.00ct each)", "3.00 Cts Total (1.50ct each)"],
    description: "The definitive jewelry wardrobe foundation. Two perfectly matched, GIA-certified 1.0-carat round brilliant diamonds in minimal 4-prong basket settings.",
    specs: { material: "18K White Gold / PT950", hallmark: "AURELISSE 750", weight: "4.1 grams per pair", gemstone: "Matched Natural Diamonds • 2.00 Cts Total • E • VVS1" }
  },
  {
    id: "ear-hoop-pav-03",
    name: "L'Anneau d'Or Pavé Diamond Hoops",
    brand: "Aurelisse Everyday",
    category: "Earrings",
    subcategory: "Hoops",
    collections: ["Earrings", "Everyday Wear", "Gold Collection", "Diamond Collection", "Minimal/Layering Pieces"],
    price: 5600,
    originalPrice: 6200,
    discount: 9.6,
    rating: 4.8,
    reviewsCount: 44,
    stockStatus: "In Stock",
    isNew: true,
    isBestSeller: true,
    isTrending: true,
    isBridalPick: false,
    badge: "Trending",
    image: "https://images.unsplash.com/photo-1611591471483-ed5f36e8979d?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1611591471483-ed5f36e8979d?auto=format&fit=crop&w=1200&q=85"],
    metals: ["18K Yellow Gold", "18K White Gold", "18K Rose Gold"],
    sizes: ["30mm Diameter (Medium)", "45mm Diameter (Large)"],
    description: "Inside-out diamond hoop earrings where round brilliant diamonds line both the outer front curve and inner back curve for continuous 360-degree sparkle.",
    specs: { material: "18K Solid Gold", hallmark: "AURELISSE 750", weight: "9.8 grams", gemstone: "Natural Diamonds • 2.40 Cts Total • F • VS1" }
  },
  {
    id: "ear-pearl-akoya-04",
    name: "L'Aurore South Sea Pearl & Diamond Drops",
    brand: "Aurelisse Pearl Collection",
    category: "Earrings",
    subcategory: "Drop Earrings",
    collections: ["Earrings", "Pearl Collection", "Bridal Collection", "Statement Pieces", "Vintage-Inspired Collection"],
    price: 6800,
    originalPrice: 7400,
    discount: 8.1,
    rating: 4.9,
    reviewsCount: 31,
    stockStatus: "In Stock",
    isNew: false,
    isBestSeller: true,
    isTrending: false,
    isBridalPick: true,
    badge: "Pearl Pick",
    image: "https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?auto=format&fit=crop&w=1200&q=85"],
    metals: ["18K White Gold", "Platinum (PT950)"],
    sizes: ["1.5 Inches Drop"],
    description: "Two flawless 12mm Golden South Sea cultured pearls suspended from Art Deco geometric tops pave-set with 1.10 carats of marquise diamonds.",
    specs: { material: "18K White Gold", hallmark: "AURELISSE 750 PEARL", weight: "12.4 grams", gemstone: "12mm Golden South Sea Pearls & 1.10 Cts Diamonds" }
  },

  // --- BRIDAL COLLECTION ---
  {
    id: "bridal-mangal-01",
    name: "Vendôme Diamond Mangalsutra Masterpiece",
    brand: "Aurelisse Bridal & Heritage",
    category: "Bridal Collection",
    subcategory: "Mangalsutra",
    collections: ["Bridal Collection", "Diamond Collection", "Gold Collection", "Everyday Wear", "Custom/Bespoke Jewellery"],
    price: 8500,
    originalPrice: 9200,
    discount: 7.6,
    rating: 5.0,
    reviewsCount: 31,
    stockStatus: "In Stock",
    isNew: true,
    isBestSeller: true,
    isTrending: true,
    isBridalPick: true,
    badge: "Bridal Heritage",
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1200&q=85"],
    metals: ["18K Yellow Gold & Black Beads", "18K Rose Gold & Black Beads"],
    sizes: ["18 Inches", "20 Inches"],
    description: "Where Parisian high-jewellery artistry honors sacred traditions. Hand-rolled black onyx beads intertwined with 18K gold chain, culminating in a modern sunburst diamond pendant.",
    specs: { material: "18K Yellow Gold & Black Onyx", hallmark: "AURELISSE 750 HERITAGE", weight: "12.8 grams", gemstone: "Natural Diamonds • 1.60 Carats Total • E • VVS1" }
  },
  {
    id: "bridal-bands-his-her-02",
    name: "L'Alliance Éternelle His & Hers Platinum Bands",
    brand: "Aurelisse Bridal",
    category: "Bridal Collection",
    subcategory: "Wedding Bands His & Hers",
    collections: ["Bridal Collection", "Platinum Collection", "Anniversary Collection", "Minimal/Layering Pieces"],
    price: 7200,
    originalPrice: 7900,
    discount: 8.8,
    rating: 5.0,
    reviewsCount: 48,
    stockStatus: "In Stock",
    isNew: false,
    isBestSeller: true,
    isTrending: false,
    isBridalPick: true,
    badge: "His & Hers Set",
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=85"],
    metals: ["Platinum (PT950)"],
    sizes: ["Custom Pair Selection (Sizes US 4 to 12)"],
    description: "A matched pair of PT950 pure Platinum wedding bands. Hers features a delicate channel of baguette diamonds (0.60ct); His features a substantial 5mm comfort-fit band.",
    specs: { material: "Pure PT950 Platinum", hallmark: "AURELISSE 950 PT", weight: "16.5 grams combined", gemstone: "Natural Baguette & Hidden Brilliant Diamonds • 0.70 Cts" }
  },

  // --- MEN'S JEWELLERY ---
  {
    id: "men-chain-plat-01",
    name: "Vendôme PT950 Platinum Heavy Franco Chain",
    brand: "Aurelisse Homme",
    category: "Men's Jewellery",
    subcategory: "Chains",
    collections: ["Men's Jewellery", "Platinum Collection", "Everyday Wear", "Gold Collection", "Statement Pieces"],
    price: 11500,
    originalPrice: 11500,
    discount: 0,
    rating: 4.9,
    reviewsCount: 18,
    stockStatus: "In Stock",
    isNew: true,
    isBestSeller: false,
    isTrending: true,
    isBridalPick: false,
    badge: "Men's High Luxury",
    image: "https://images.unsplash.com/photo-1622434641406-a158123450f9?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1622434641406-a158123450f9?auto=format&fit=crop&w=1200&q=85"],
    metals: ["Platinum (PT950)", "18K Yellow Gold"],
    sizes: ["22 Inches (4mm)", "24 Inches (4mm)"],
    description: "Masterfully hand-linked PT950 Platinum four-sided V-link Franco chain with substantial weight and our architectural lobster clasp adorned with a single black diamond.",
    specs: { material: "Pure PT950 Platinum", hallmark: "AURELISSE 950 PT HOMME", weight: "62.0 grams (22 inch)", gemstone: "0.10ct Black Diamond on Clasp" }
  },
  {
    id: "men-cuff-dia-02",
    name: "L'Empereur Onyx & Diamond Cufflinks",
    brand: "Aurelisse Homme",
    category: "Men's Jewellery",
    subcategory: "Cufflinks",
    collections: ["Men's Jewellery", "Diamond Collection", "Everyday Wear", "Accessories", "Anniversary Collection"],
    price: 3600,
    originalPrice: 4000,
    discount: 10,
    rating: 5.0,
    reviewsCount: 15,
    stockStatus: "In Stock",
    isNew: false,
    isBestSeller: true,
    isTrending: false,
    isBridalPick: false,
    badge: "Gentleman's Essential",
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=85"],
    metals: ["18K White Gold", "18K Yellow Gold"],
    sizes: ["Standard Cuff Fit"],
    description: "Sleek octagonal cufflinks in 18K White Gold framing polished black onyx batons with diamond-paved borders. The ultimate finish for French cuffs.",
    specs: { material: "18K White Gold & Onyx", hallmark: "AURELISSE 750 HOMME", weight: "12.4 grams per pair", gemstone: "Black Onyx & 0.60 Cts Natural Diamonds" }
  },

  // --- KIDS' JEWELLERY ---
  {
    id: "kids-brac-baby-01",
    name: "Petite Étoile 18K Gold Baby Identification Bangle",
    brand: "Aurelisse Enfant",
    category: "Kids' Jewellery",
    subcategory: "Baby Bracelets",
    collections: ["Kids' Jewellery", "Bracelets", "Gold Collection", "Everyday Wear"],
    price: 950,
    originalPrice: 950,
    discount: 0,
    rating: 5.0,
    reviewsCount: 29,
    stockStatus: "In Stock",
    isNew: false,
    isBestSeller: true,
    isTrending: false,
    isBridalPick: false,
    badge: "Precious Gift",
    image: "https://images.unsplash.com/photo-1543294001-f7cd5d7fb516?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1543294001-f7cd5d7fb516?auto=format&fit=crop&w=1200&q=85"],
    metals: ["18K Yellow Gold", "18K Rose Gold"],
    sizes: ["Infant (0-2 Years)", "Toddler (2-5 Years)"],
    description: "A smooth, rounded 18K gold expandable bangle featuring a polished nameplate ready for custom hand engraving, accented by a tiny flush-set diamond star.",
    specs: { material: "Solid 18K Hypoallergenic Gold", hallmark: "AURELISSE 750 ENFANT", weight: "4.8 grams", gemstone: "Natural Diamond • 0.05 Carat • Flush Secure Bezel" }
  },

  // --- WATCHES ---
  {
    id: "watch-complication-01",
    name: "L'Heure Impériale Tourbillon Pavé Watch",
    brand: "Aurelisse Timepieces",
    category: "Watches",
    subcategory: "Ladies Mechanical",
    collections: ["Watches", "Diamond Collection", "Statement Pieces", "Gold Collection", "Custom/Bespoke Jewellery"],
    price: 68000,
    originalPrice: 75000,
    discount: 9.3,
    rating: 5.0,
    reviewsCount: 8,
    stockStatus: "In Stock (Only 1 Made)",
    isNew: true,
    isBestSeller: false,
    isTrending: true,
    isBridalPick: false,
    badge: "Horological Art",
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=85"],
    metals: ["18K Rose Gold", "18K White Gold"],
    sizes: ["36mm Case • Satin Strap"],
    description: "Swiss hand-wound tourbillon movement housed inside an 18K Rose Gold case completely hand-paved with 440 snow-set brilliant diamonds (5.8 carats total).",
    specs: { material: "18K Rose Gold & Alligator", hallmark: "SWISS MADE / CALIBRE 01", weight: "58.0 grams", gemstone: "440 Natural Diamonds • 5.80 Cts • Mother of Pearl Dial" }
  },

  // --- ACCESSORIES ---
  {
    id: "acc-box-velvet-01",
    name: "Vendôme Italian Leather & Velvet Trunk Box",
    brand: "Aurelisse Accessories",
    category: "Accessories",
    subcategory: "Jewellery Boxes",
    collections: ["Accessories", "Everyday Wear", "Anniversary Collection"],
    price: 1450,
    originalPrice: 1450,
    discount: 0,
    rating: 4.9,
    reviewsCount: 45,
    stockStatus: "In Stock",
    isNew: false,
    isBestSeller: true,
    isTrending: false,
    isBridalPick: false,
    badge: "Luxury Accessory",
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=85",
    images: ["https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=85"],
    metals: ["Gold-Plated Brass Hardware"],
    sizes: ["12 x 9 x 6 Inches"],
    description: "Handcrafted in Florence using supple cream full-grain calfskin exterior and anti-tarnish ivory microfiber plush interior with specialized drawers for rings, chains, and watches.",
    specs: { material: "Italian Calfskin & Velvet", hallmark: "AURELISSE FIRENZE", weight: "2.4 kg", gemstone: "Custom gold monogramming plate included" }
  }
];

export const JOURNAL_POSTS = [
  {
    id: "post-01",
    title: "The Anatomy of Place Vendôme High Jewellery",
    category: "Craftsmanship & Heritage",
    date: "July 8, 2026",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1589674781759-c21c37956a44?auto=format&fit=crop&w=800&q=80",
    summary: "Step inside our Parisian atelier where master artisans dedicate upwards of 800 hours to hand-forging a single articulated diamond rivière...",
    content: "For over a century, the House of Aurelisse has stood at the crossroads of artistic courage and technical mastery. In our Place Vendôme atelier, the creation of a high-jewellery masterpiece begins not with metal, but with gouache—a watercolor painting rendered at exact 1:1 scale by our head designer."
  },
  {
    id: "post-02",
    title: "How to Care for Heirloom Diamond & Pearl Pieces",
    category: "Jewellery Care Guide",
    date: "June 22, 2026",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?auto=format&fit=crop&w=800&q=80",
    summary: "Diamonds are forever, but their settings require tender reverence. Learn our master jewelers' protocol for preserving luster across generations...",
    content: "While diamonds rank 10 on the Mohs hardness scale, the precious metals—18K gold and pure platinum—that hold them are malleable by nature. We recommend the golden rule of fine jewellery: your pieces should be the last thing you put on before leaving, and the first thing you take off upon returning home."
  },
  {
    id: "post-03",
    title: "The Bridal Curations: Finding Your Signature Ring",
    category: "Styling Guides",
    date: "May 14, 2026",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80",
    summary: "From the architectural purity of emerald cuts to the romantic fire of oval brilliants, discover how your diamond shape reflects your personal aesthetic...",
    content: "When selecting an engagement ring or bridal set, balance between finger architecture and stone geometry is paramount. An emerald cut speaks to those who cherish Art Deco symmetry and clean lines, whereas the oval brilliant elongated silhouette creates an illusion of slender, graceful fingers."
  }
];

export const FAQS = [
  {
    q: "Are all Aurelisse diamonds and gemstones certified?",
    a: "Yes. Every single Aurelisse diamond above 0.30 carats comes accompanied by an official, independent grading monograph from the Gemological Institute of America (GIA) or HRD Antwerp. Our rare colored gemstones (such as Burmese Rubies and Colombian Emeralds) are certified by Gubelin or SSEF Swiss laboratories."
  },
  {
    q: "What is your return and exchange policy?",
    a: "We offer a gracious 30-day return and exchange policy on all non-bespoke and non-engraved pieces. The item must be returned in its original, unworn condition with all authenticity certificates and luxury presentation trunks intact."
  },
  {
    q: "How does the Order via WhatsApp concierge service work?",
    a: "Clicking 'Order via WhatsApp' on any product page or in your shopping cart connects you instantly to a live Place Vendôme or regional luxury concierge via WhatsApp. Your message is pre-filled with the exact piece specifications (Metal, Size, Price, SKU), allowing our team to arrange private consultation, bespoke sizing, and white-glove insured delivery."
  },
  {
    q: "Do you offer international white-glove shipping?",
    a: "Yes. We ship worldwide via armored, fully insured express courier (Brinks / FedEx Priority VIP). Shipping is complimentary on all orders exceeding $2,500."
  },
  {
    q: "Can I book a private in-store or virtual video consultation?",
    a: "Absolutely. Our 'Book an Appointment' portal allows you to reserve a 60-minute one-on-one session with a Senior Gemologist either in our Paris, London, New York, or Tokyo salons, or via 4K high-definition video link."
  }
];

export const TIMELINE = [
  { year: "1894", title: "The Foundation", desc: "Henri Aurelisse opens his first boutique on Rue de la Paix, catering to European nobility and discerning collectors." },
  { year: "1926", title: "The Art Deco Revolution", desc: "Aurelisse introduces the iconic 'Lumière' geometric diamond setting, winning the Grand Prix in Paris." },
  { year: "1972", title: "The Place Vendôme Salon", desc: "The flagship headquarters moves to the prestigious Place Vendôme, solidifying our place among the world's elite jewellery houses." },
  { year: "2015", title: "100% Ethical & Conflict-Free", desc: "Aurelisse becomes one of the first high jewellery houses to certify 100% recycled precious metals and blockchain-traced diamonds." },
  { year: "2026", title: "L'Éclat Digital Experience", desc: "Launch of our award-winning digital luxury boutique, bringing the personalized touch of Place Vendôme directly to clients worldwide." }
];

export const TESTIMONIALS = [
  { quote: "Receiving our bespoke Aurelisse engagement ring felt like stepping into royal history. The packaging, the weight of the platinum, the fire of the diamond—perfection.", author: "Lady Victoria H.", location: "London & Zurich", rating: 5 },
  { quote: "The online WhatsApp concierge was exceptionally attentive. They filmed a 4K video of the sapphire chandelier earrings under different lighting before I made my purchase.", author: "Marcello D.", location: "Milan", rating: 5 },
  { quote: "Aurelisse captures true quiet luxury. No loud logos—just breathtaking stones and craftsmanship that speaks for itself across the room.", author: "Camilla S.", location: "New York", rating: 5 }
];

export const OFFERS_DATA = [
  { title: "Festive Place Vendôme Launch", subtitle: "Complimentary Solid 18K Gold Travel Pouch & $500 Gift Voucher on orders over $5,000.", code: "FESTIVE20", discount: "20% OFF SELECT COLLECTIONS", expiresInDays: 5 },
  { title: "The Bridal & Anniversary Offer", subtitle: "Receive complimentary custom diamond laser engraving inside any wedding band or solitaire ring purchase.", code: "BRIDALGIFT", discount: "FREE CUSTOM ENGRAVING ($350 VALUE)", expiresInDays: 12 },
  { title: "First Light Circle Welcome", subtitle: "Join our inner circle for an exclusive welcome reduction on your first high jewellery acquisition.", code: "AURELISSE10", discount: "10% PRIVILEGE REDUCTION", expiresInDays: 30 }
];
